### PR TITLE
Support to set environment variables.

### PR DESCRIPTION
**Pull request by erikh**
@mapuri @gaurav-dalvi

### CODE REVIEW

**Comment by mapuri** [comment]
thanks @erikh LGTM

This is certainly a useful enhancement.

I think if I understood @gaurav-dalvi case, he was looking for a way to pass different environment per command (like setting DOCKER_HOST to swarm's IP:PORT in one command and setting it to local docker engine's IP:PORT in another), without having to modify the command string. But I am not very sure. If so, we may need to add `env` per Run\* Method of `SSHNode`, like one example below, wdyt?

```
func (n *SSHNode) RunCommand(env []string, cmd string) error
```

**Comment by erikh** [comment]
btw, I couldn't use setenv because the default ssh configuration will block it.

**Comment by erikh** [comment]
@mapuri: Let's wait for @gaurav-dalvi to answer before merging this then

**Comment by erikh** [comment]
personally, I think the system should have support for both, but if gaurav can move with this support, I'd like to leave it here for now if that's ok.

**Comment by mapuri** [comment]
yes definitely, sounds good to me !

**Comment by gaurav-dalvi** [comment]
So Original Code in runContainer function in node_test.go:

cmd = fmt.Sprintf("docker run -itd %s %s %s %s %s", namestr, netstr, dnsStr, spec.imageName, spec.commandName)

If I use this same function in Swarm setup, It does not work as We need to set DOCKER_HOST env variable prior to this.

We have two options here :
1: On those predefined VMs (where we will run this ACI automation), we will have this export statement in bashrc and then use this function as it is. Right now it works for me.

2: I just need to change that one line above to

cmd = fmt.Sprintf( $DOCKER_HOST + " docker run -itd %s %s %s %s %s", namestr, netstr, dnsStr, spec.imageName, spec.commandName)

The functionality added by @erikh Certainly will help in future and I feel this one is great feature to have it in vagrantssh library.

What I feel is : having these type of functions (runContainer) separate for Swarm, K8s, Nomad etc and then duplicate or reuse this code. We can have interface for this and then implement this depending upon the environment which we are running these tests (Swarm, Plain docker, K8s etc).

Still open ended question is : 

If you get PR with runContainer function separate of Swarm and Docker with just that line of change, Will you approve it or not. 

I dont have answer but But I feel two runContainer implementations depending upon Orchestration engine, is way to go but we need to check how much different in the code that needs. This approach just makes systemtest code bigger but as long as it works seamlessly on all orchestration engines and whether its baremetal VM or vagrant VM, we should be fine.

I am ok with feature and I think we should merge this.

**Comment by erikh** [comment]
@mapuri merge when you are comfortable

**Comment by mapuri** [comment]
@gaurav-dalvi 

> If you get PR with runContainer function separate of Swarm and Docker with just that line of change, Will you approve it or not. 

This is a good point to worry about. And I don't think the question is about approving a PR for starting containers in vagrantssh. But it is more about the scope of a library.

I like to think about this as following hypothetical scenario. Consider yourself the maintainer of a library that provides a function to add two **things**. Now one client of this lib can use it to add integers while another can do it for floats and another one can do it for strings. For sure all these functions could have been a part of the library itself (than each client implementing their specific thing on top of the library). And it might be hard to argue why you wouldn't do it in the library at this point. So let's say you decide to do it in the library. Now, another user wants to do it for their private data ( i.e. add a non standard datatype). What should you do as a maintainer when you get the PR? Leaving it out will make the library inconsistent. And taking the change will need your library to understand the user's private data. Should you have seen it when you decided to bring in first user's request who just needed it for integers?

It is certainly not always as simple a situation as above but hopefully you see the problem. vagrantssh library is supposed to provide functionality to run commands on a testnode. Should it care whether the commands starts a container or copies a file?

On similar lines this PR actually adheres to the library's scope as it makes running commands easier without solving for a specific command.

**Comment by gaurav-dalvi** [comment]
+1 to @mapuri .

I am trying to build generic systemtests here. Currently our systemtests are tied to vagrant.

I think my problem is more of how to design this in object oriented fashion.
This is  a library which make things easier for us. The problem I am trying to resolve it to have common infra for automated testing using this library. I dont want code to get duplicated.

Simple Case:

We have two mechanisms to bring VMs:
1: Using vagrant
2: Using VMs which is running on some Hypervisor in traditional lab (e.g ESX)

And we have following things to tackle  : 
1: Plain docker mode of netplugin and netmaster
2: On K8s
3: On Swarm
4: On Mesos
5: on Nomad
...

If you guys have suggestion on how can I make this design and code modular and object oriented , then we can do right design and then later on adding nomad or mesos will be very easy.

**Comment by erikh** [comment]
I think the minimalist approach here is preferred; we just really need environment passing per-command.

The baremetal situation should cover all things this library should do: ssh into things and run other things.

**Pull request merged**
