### PR TITLE
fix a compilation issue

### PR DESCRIPTION
**Pull request by mapuri**

### CODE REVIEW

**Comment by mapuri** [comment]
don't merge yet...somehow CI didn't get triggered..I am looking into it

**Comment by mapuri** [comment]
ok, this is ready for a look.

**Comment by mapuri** [comment]
it's an obvious fix so will merge it once sanity passes

**Comment by erikh** [comment]
Sorry I think you'll have to fix the golint issue too.

Also, I haven't run into these compilation issues yet.

**Comment by mapuri** [comment]
I have fixed the golint error...

>  I haven't run into these compilation issues yet.

I think if you don't store `*Vagrant` object in a `Tesbed` type (which can be useful when dealing with different testbed types say baremetal, vagrant etc) , you won't see this failure. I made a fix to tests as well to catch this i.e. if it shall catch if `*Vagrant` doesn't conform to `Testbed` interface

**Comment by erikh** [comment]
Makes sense.

**Pull request merged**
