### PR TITLE
Edited the README to include package name change

### PR DESCRIPTION
**Pull request by apoorva11029**

### CODE REVIEW

**Comment by erikh** [comment]
Beautiful! Can you squash and rebase?

**Comment by erikh** [comment]
just to clarify; there's brokenness in the API hooks, not the commits here.

**Comment by mapuri** [comment]
looks like the jenkins github hooks were not working after the recent repo name change. 

I have made some changes on CI side. 

@gaurav-dalvi can you re-push your changes, let's see if it triggers the CI now.

**Comment by mapuri** [comment]
oops I meant @apoorva11029 , not Gaurav :)

**Comment by mapuri** [comment]
LGTM

**Pull request merged**
